components:
  compile_model: false
  compile_dynamic: false
  activation_checkpointing: false

pretraining:
  use_amp: false

mining:
  use_faiss_gpu: false

alignment:
  query_pool_use_flash: false
  use_amp: false

api:
  osu_api_version: "20241024"
  max_recommend_top_k: 200
  default_recommend_beatmap_ids: [
    1872396, # tsukinmai
    658127, # blue zenith
    1351114, # cycle hit
    2535968, # yoru ni kakeru
    2809623, # kemomimi
    4881796, # zenithfall
    3592622, # popular
    724015, # toumei elegy
    1031991, # yomi yori
    2872154, # lionheart
    2736518, # keshin
    3333745, # rpg
    2250670, # unhappy refrain
    1380717, # logical stimulus
    2719326, # sputnik-3
    555797, # time freeze
    1988753, # ai no sukima
    2096523, # gera gera
    1419243, # hibana
    1787848, # exit this earth's atomosphere
  ]
  rate_limits:
    global_recommend_per_hour: 1200
    server_recommend_per_hour: 600
    ip_recommend_per_hour: 120
