[project]
name = "osu_corpora"
version = "0.1.0"
description = "universal embedding encoder for osu beatmaps"
requires-python = ">=3.12"

# Core dependencies (equivalent to requirements.txt)
dependencies = [
    "torch",
    "numpy",
    "pandas",
    "tqdm",
    "gdown",
    "pyarrow>=21.0.0",
    "ossapi>=5.3.3",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "torchmetrics>=1.8.2",
]

[project.optional-dependencies]
# Dependencies for development, like notebooks or linters
dev = [
    "notebook",
    "jupyterlab",
    "ruff" # A great, fast linter that uv is built on!
]
