/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Default Recommend */
        get: operations["default_recommend_api_recommend_get"];
        put?: never;
        /** Recommend */
        post: operations["recommend_api_recommend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beatmaps/{beatmap_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Beatmap Detail */
        get: operations["beatmap_detail_api_beatmaps__beatmap_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/beatmaps/{beatmap_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Beatmap Summary */
        get: operations["beatmap_summary_api_beatmaps__beatmap_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BeatmapSummary */
        BeatmapSummary: {
            /** Beatmap Id */
            beatmap_id: number;
            /** Beatmapset Id */
            beatmapset_id: number | null;
            /** Artist */
            artist: string | null;
            /** Title */
            title: string | null;
            /** Creator */
            creator: string | null;
            /** User Id */
            user_id: number | null;
            /** Version */
            version: string | null;
            /** Status */
            status: string | number | null;
            /** Stars */
            stars: number | null;
            /** Ar */
            ar: number | null;
            /** Cs */
            cs: number | null;
            /** Accuracy */
            accuracy: number | null;
            /** Drain */
            drain: number | null;
            /** Bpm */
            bpm: number | null;
            /** Total Length */
            total_length: number | null;
            /** Last Updated */
            last_updated: string | null;
            /** Ranked Date */
            ranked_date: string | null;
            /** Submitted Date */
            submitted_date: string | null;
            /** Release Date */
            release_date: string | null;
            /** Url */
            url: string;
        };
        /**
         * DateWindow
         * @enum {string}
         */
        DateWindow: "last_week" | "last_month" | "last_3_months" | "last_6_months" | "last_year" | "last_2_years" | "last_5_years" | "all_time";
        /** DefaultRecommendResponse */
        DefaultRecommendResponse: {
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["BeatmapSummary"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RecommendFilters */
        RecommendFilters: {
            /** Min Sr */
            min_sr?: number | null;
            /** Max Sr */
            max_sr?: number | null;
            /** Min Ar */
            min_ar?: number | null;
            /** Max Ar */
            max_ar?: number | null;
            /** Min Cs */
            min_cs?: number | null;
            /** Max Cs */
            max_cs?: number | null;
            /** Min Accuracy */
            min_accuracy?: number | null;
            /** Max Accuracy */
            max_accuracy?: number | null;
            /** Min Drain */
            min_drain?: number | null;
            /** Max Drain */
            max_drain?: number | null;
            /** Min Bpm */
            min_bpm?: number | null;
            /** Max Bpm */
            max_bpm?: number | null;
            /** Min Length */
            min_length?: number | null;
            /** Max Length */
            max_length?: number | null;
            /** Status */
            status?: string | null;
            date_window?: components["schemas"]["DateWindow"] | null;
            /**
             * Exclude Same Set
             * @default true
             */
            exclude_same_set: boolean;
        };
        /** RecommendRequest */
        RecommendRequest: {
            /** Beatmap Ids */
            beatmap_ids: number[];
            /**
             * Top K
             * @default 20
             */
            top_k: number;
            filters?: components["schemas"]["RecommendFilters"];
        };
        /** RecommendResponse */
        RecommendResponse: {
            /** Sources */
            sources: components["schemas"]["RecommendSource"][];
            /** Count */
            count: number;
            /** Results */
            results: components["schemas"]["ScoredBeatmapSummary"][];
        };
        /** RecommendSource */
        RecommendSource: {
            /** Beatmap Id */
            beatmap_id: number;
            /**
             * Cache
             * @enum {string}
             */
            cache: "hit" | "miss";
            metadata: components["schemas"]["BeatmapSummary"];
        };
        /** ScoredBeatmapSummary */
        ScoredBeatmapSummary: {
            /** Beatmap Id */
            beatmap_id: number;
            /** Beatmapset Id */
            beatmapset_id: number | null;
            /** Artist */
            artist: string | null;
            /** Title */
            title: string | null;
            /** Creator */
            creator: string | null;
            /** User Id */
            user_id: number | null;
            /** Version */
            version: string | null;
            /** Status */
            status: string | number | null;
            /** Stars */
            stars: number | null;
            /** Ar */
            ar: number | null;
            /** Cs */
            cs: number | null;
            /** Accuracy */
            accuracy: number | null;
            /** Drain */
            drain: number | null;
            /** Bpm */
            bpm: number | null;
            /** Total Length */
            total_length: number | null;
            /** Last Updated */
            last_updated: string | null;
            /** Ranked Date */
            ranked_date: string | null;
            /** Submitted Date */
            submitted_date: string | null;
            /** Release Date */
            release_date: string | null;
            /** Url */
            url: string;
            /** Score */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    default_recommend_api_recommend_get: {
        parameters: {
            query?: {
                seed?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DefaultRecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_api_recommend_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    beatmap_detail_api_beatmaps__beatmap_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beatmap_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    beatmap_summary_api_beatmaps__beatmap_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                beatmap_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BeatmapSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
