defaults:
  - base

data:
  # db_path: './data/beatmaps_test.db'
  db_path: './data/beatmaps.db'
model:
  type: "bert"
  d_model: 512
  n_heads: 8
  n_layers: 6
  dim_feedforward_mult: 4

training:
  checkpoint_dir: "./checkpoints/bert"
  sampling:
    method: "temperature"  
    kde_bandwidth: 0.3  
    kde_bins: 200     
    temperature: 2.0  
    difficulty_index: 3 
    expand_for_augmentation: true

mlm:
  masking_ratio: 0.25
  
components:
  use_rope: true
  use_flash_attention: true
  compile_model: true